config/routes.rb
Rails.application.routes.draw do

  resources :pc_iotros
  resources :pp_fjos
  resources :rfc_fjos
  resources :pc_fjos
  resources :fuente_financiamientos
  resources :tecnico_administrativos
  resources :vinculos
  resources :ae_is
  resources :ae_lis
  resources :ae_pos
  resources :articulo_entrevistas
  resources :aporte_actividades
  resources :pp_pos
  resources :pp_is
  resources :producto_pmes
  resources :ad_is
  resources :ad_pos
  resources :actividad_difusiones
  resources :rc_is
  resources :r_colaboraciones
  resources :rfc_as
  resources :rfc_is
  resources :rf_colaboraciones
  resources :pasantia_externos
  resources :pasantia_internos
  resources :tf_lis
  resources :tesis_finalizadas
  resources :fj_is
  resources :fj_dis
  resources :nivel_formaciones
  resources :formacion_jovenes
  resources :ci_is
  resources :comite_editoriales
  resources :pyh_centros
  resources :pyh_investigadores
  resources :pc_is
  resources :presentacion_congresos
  resources :pat_pais
  resources :paises
  resources :patentes
  resources :pis
  resources :p_lis
  resources :publicaciones
  resources :aco_pos
  resources :publico_objetivos
  resources :acos
  resources :i_dis
  resources :i_lis
  resources :grado_academicos
  resources :li_dis
  resources :investigadores
  resources :disciplinas
  resources :linea_investigaciones
  resources :datos_centros

  scope module: 'aplicacion' do
    resources :app_administradores
    resources :app_nominas
    resources :app_perfiles do
      match :desvincular, via: :get, on: :member
    end

    resources :app_recursos do
      collection do
        match :ayuda, via: :get
        match :home, via: :get
        match :ingreso_datos_anuales, via: :get
        match :administracion, via: :get
        match :procesos, via: :get
      end
    end

    resources :app_documentos
    resources :app_dir_dires
    resources :app_directorios do
      match :nuevo, via: :post, on: :collection
    end
    resources :app_repos do
      match :publico, via: :get, on: :collection
      match :perfil, via: :get, on: :collection
    end
    resources :app_archivos

    resources :recursos do
      collection do
        match :ayuda, via: :get
        match :home, via: :get
        match :inicia_sesion, via: :get
        match :procesos, via: :get
        match :administracion, via: :get
        match :borrar_archivos, via: :get
      end
    end
    resources :perfiles do
      match :desvincular, via: :get, on: :member
    end
    resources :administradores
    resources :nominas
    resources :archivos
    resources :imagenes
    resources :directorios do
      match :nuevo, via: :post, on: :collection
    end
    resources :subs
    resources :documentos do
      resources :archivos
    end
  end

  scope module: 'home' do
    resources :h_imagenes
    resources :h_links
    resources :h_temas
  end
  
  scope module: 'sidebar' do
    resources :sb_elementos
    resources :sb_listas do
      resources :sb_elementos
    end
  end

  scope module: 'help' do
    resources :hlp_tutoriales do
      resources :hlp_pasos
    end
    resources :hlp_pasos
#    resources :conversaciones
    resources :mensajes
    resources :pasos
    resources :tema_ayudas do
      resources :tutoriales
    end
    resources :tutoriales do
      resources :pasos
    end
  end

  devise_for :usuarios, controllers: {
        confirmations: 'usuarios/confirmations',
#        omniauth_callbacks: 'usuarios/omniauth_callbacks',
        passwords: 'usuarios/passwords',
        registrations: 'usuarios/registrations',
        sessions: 'usuarios/sessions',
        unlocks: 'usuarios/unlocks'
      }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

#  root 'aplicacion/recursos#home'
  root 'aplicacion/app_recursos#ingreso_datos_anuales'
  
end

app/controllers/paises_controller.rb
class PaisesController < ApplicationController
  before_action :set_pais, only: %i[ show edit update destroy ]

  # GET /paises or /paises.json
  def index
    @coleccion = Pais.all
  end

  # GET /paises/1 or /paises/1.json
  def show
  end

  # GET /paises/new
  def new
    @objeto = Pais.new
  end

  # GET /paises/1/edit
  def edit
  end

  # POST /paises or /paises.json
  def create
    @objeto = Pais.new(pais_params)

    respond_to do |format|
      if @objeto.save
        set_redireccion
        format.html { redirect_to @redireccion, notice: "Pais was successfully created." }
        format.json { render :show, status: :created, location: @objeto }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @objeto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /paises/1 or /paises/1.json
  def update
    respond_to do |format|
      if @objeto.update(pais_params)
        set_redireccion
        format.html { redirect_to @redireccion, notice: "Pais was successfully updated." }
        format.json { render :show, status: :ok, location: @objeto }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @objeto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /paises/1 or /paises/1.json
  def destroy
    set_redireccion
    @objeto.destroy
    respond_to do |format|
      format.html { redirect_to @redireccion, notice: "Pais was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pais
      @objeto = Pais.find(params[:id])
    end

    def set_redireccion
      @redireccion = '/recursos/administracion?t=Países'
    end

    # Only allow a list of trusted parameters through.
    def pais_params
      params.require(:pais).permit(:pais)
    end
end

app/helpers/paises_helper.rb
module PaisesHelper
end

app/views/paises/_form.html.erb
<%= form_with(model: pais, local: true) do |form| %>
  <% if pais.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pais.errors.count, "error") %> prohibited this pais from being saved:</h2>

      <ul>
      <% pais.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :pais %>
    <%= form.text_field :pais %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/paises/edit.html.erb
<h1>Editing Pais</h1>

<%= render 'form', pais: @pais %>

<%= link_to 'Show', @pais %> |
<%= link_to 'Back', paises_path %>

app/views/paises/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Paises</h1>

<table>
  <thead>
    <tr>
      <th>Pais</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @paises.each do |pais| %>
      <tr>
        <td><%= pais.pais %></td>
        <td><%= link_to 'Show', pais %></td>
        <td><%= link_to 'Edit', edit_pais_path(pais) %></td>
        <td><%= link_to 'Destroy', pais, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pais', new_pais_path %>

app/views/paises/new.html.erb
<h1>New Pais</h1>

<%= render 'form', pais: @pais %>

<%= link_to 'Back', paises_path %>

app/views/paises/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Pais:</strong>
  <%= @pais.pais %>
</p>

<%= link_to 'Edit', edit_pais_path(@pais) %> |
<%= link_to 'Back', paises_path %>